name: Scrape Laptop Prices

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:        # allows manual run

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright beautifulsoup4
          playwright install chromium

      - name: Run scraper
        run: python scrape_sites.py

      - name: Commit & push updated data
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add data/products.json
          git commit -m "Update scraped data" || echo "No changes"
          git push
